name: Testing Buttbot

on:
  pull_request:
    branches:
      - "*"
  push:
    branches:
      - master

jobs:
  test:
    runs-on: ubuntu-20.04
    container: node:14.16-buster-slim
    steps:
      - uses: actions/checkout@v1
      - name: yarn, build, and test
        run: |
          yarn
          yarn run test
          yarn run build
